development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: postgres
  password: 123
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: postgres
  password: 123
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  username: postgres
  password: 123
  host: localhost
